name: egym_nfc_pass_wallet
description: Flutter plugin for EGYM NFC pass wallet integration.
version: 0.1.0
homepage: https://github.com/egym/lib-capacitor-nfc-pass-wallet

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.egym.flutter.nfcpasswallet
        pluginClass: EgymNfcPassWalletPlugin
      ios:
        pluginClass: EgymNfcPassWalletPlugin
